image: ubuntu:16.04

before_script:
  - apt-get update --quiet
  - apt-get install --yes build-essential gcc-multilib bc kernel-package libncurses5-dev bzip2 liblz4-tool
  - chmod +x build.sh
  - mkdir Builds
  - cd Builds
  - mkdir Oreo
  - cd ..

stages:
  - build

build:
  stage: build
  script:
    - ./build.sh
  artifacts:
    paths:
    - Builds
    expire_in: 1 week

